source "http://rubygems.org"

gem 'sinatra'
gem 'sinatra-reloader'
gem 'redcarpet'
gem 'tilt'
gem 'haml'
gem 'sass'
gem 'rack'
gem 'albino'
gem 'nokogiri'
gem 'launchy'
gem 'ffi', '1.0.9'
gem 'pygments.rb'
gem 'thin'